### PR TITLE
Added exception handling to worker call

### PR DESCRIPTION
**Pull request by blazer82**
I ran into problems with errors being thrown within worker functions when used with meteor job collection. It seems the problem needed to be fixed here. There's also a corresponding pull request for meteor-job-collection adding the appropriate unit test.

### CODE REVIEW

**Comment by vsivsi** [comment]
Hi, Thanks for the PR, but If I'm reading this correctly, it just catches the exception and silently swallows it???  I'm struggling to think of a situation in which that is the correct or expected behavior.

When someone authors a worker function and it makes calls that can throw, then that needs to be caught and handled within the worker function itself, not within the `processJobs` code. I see that you are trying to make the job queue more "robust" by handling it in this way, but I don't agree that allowing throws that should be noticed, caught and handled by the calling code should just be silenced.

There have been multiple issues filed because people have encountered unexpected execution paths through their worker function causing it to return without invoking the callback (including unhandled throws), resulting in "stuck queues".  So perhaps something needs to be done to make these cases a bit easier to detect and diagnose.

Given that, if the `catch` in this PR is ever reached, then I would argue that the correct thing to do is to log a fatal error to that job on the server, emit a huge `stderr` banner about the failure, and then shut down the entire worker process. This kind of thing should never pass silently, IMO.

**Comment by vsivsi** [comment]
Just one more bit of info on this. `processJobs` is very similar in spirit to the `queue` functionality in the node.js async library. A worker function that takes a task and callback. It doesn't do any "automatic"
exception handling on behalf of its workers. That has been proposed and rejected (after much discussion) on that project multiple times by much the same reasoning I applied above.  See:

https://github.com/caolan/async/pull/396
https://github.com/caolan/async/pull/707

**Comment by vsivsi** [comment]
If you want this behavior in your own project (which I don't recommend), then you can always just do:

```js

throwEater = function (worker) {
   return function (job, cb) {
      try {
         worker(job, cb);
      } catch (err) {
         console.error("Worker just threw error:", err);
         cb()
      } 
   }
}

q = jc.processJobs('myjobs', throwEater(function (job, cb) {
   // Do work that might throw
   cb()
}));
```

**Comment by blazer82** [comment]
Thanks for considering and responding quickly! I can see your reasoning and I respect your decision, of course. My intent wasn't to silently swallow any exception. For me the best behavior when a job fails would be to mark it as failed and log the error. My changes should do all of that except for the error logging. That's still missing.

At the moment, when a job fails due to an exception the whole queue is terminated and the job just keeps its running state. I'll implement a solution within my application to prevent that as you suggested. Thank you!

**Comment by vsivsi** [comment]
Yes, I think it is best if worker functions handle all of their own failure cases, even if it is a bit more work upfront for the developer.

**Pull request closed without merging**
